/mm_arm/controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints:
          - mm_arm_shoulder_pan_joint
          - mm_arm_shoulder_lift_joint
          - mm_arm_elbow_joint
          - mm_arm_wrist_1_joint
          - mm_arm_wrist_2_joint
          - mm_arm_wrist_3_joint
        command_interfaces:
          - position
        state_interfaces:
          - position
          - velocity
        allow_partial_joints_goal: true
        state_publish_rate: 50.0
        action_monitor_rate: 20.0
        constraints:
          goal_time: 2.0
          stopped_velocity_tolerance: 0.01
          mm_arm_shoulder_pan_joint: {trajectory: 0.05, goal: 0.02}
          mm_arm_shoulder_lift_joint: {trajectory: 0.05, goal: 0.02}
          mm_arm_elbow_joint: {trajectory: 0.05, goal: 0.02}
          mm_arm_wrist_1_joint: {trajectory: 0.05, goal: 0.02}
          mm_arm_wrist_2_joint: {trajectory: 0.05, goal: 0.02}
          mm_arm_wrist_3_joint: {trajectory: 0.05, goal: 0.02}
