/mm_base/controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController
      ros__parameters:
        use_stamped_vel: false
        cmd_vel_timeout: 0.5
        publish_rate: 50.0
        enable_odom_tf: true
        base_frame_id: mm_base_base_link
        odom_frame_id: mm_base_odom

        # Mantener estos valores en sincron√≠a con mm_base_description/urdf/mm_base.urdf.xacro
        wheel_separation_x: 0.33   # distancia eje delantero-trasero (m)
        wheel_separation_y: 0.33   # distancia eje izquierdo-derecho (m)
        wheel_radius: 0.06

        front_left_wheel_name: mm_base_front_left_wheel_joint
        front_right_wheel_name: mm_base_front_right_wheel_joint
        rear_left_wheel_name: mm_base_rear_left_wheel_joint
        rear_right_wheel_name: mm_base_rear_right_wheel_joint

        linear.x.max_velocity: 1.0
        linear.x.max_acceleration: 1.0
        linear.y.max_velocity: 1.0
        linear.y.max_acceleration: 1.0
        angular.z.max_velocity: 1.5
        angular.z.max_acceleration: 2.0
