move_group:
  ros__parameters:
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
    moveit_simple_controller_manager:
      controller_names:
        - arm_trajectory_controller
      arm_trajectory_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - mm_arm_shoulder_pan_joint
          - mm_arm_shoulder_lift_joint
          - mm_arm_elbow_joint
          - mm_arm_wrist_1_joint
          - mm_arm_wrist_2_joint
          - mm_arm_wrist_3_joint
