move_group:
  ros__parameters:
    planning_pipelines:
      pipeline_names: ["ompl"]
    ompl:
      planning_plugins:
        - ompl_interface/OMPLPlanner
      request_adapters:
        - default_planning_request_adapters/CheckStartStateBounds
        - default_planning_request_adapters/ValidateWorkspaceBounds
        - default_planning_request_adapters/CheckStartStateCollision
        - default_planning_request_adapters/ResolveConstraintFrames
        - default_planning_request_adapters/CheckForStackedConstraints
      response_adapters:
        - default_planning_response_adapters/ValidateSolution
      progress_topic: ""
      start_state_max_bounds_error: 0.1
      default_planner_config: RRTConnectkConfigDefault
      planner_configs:
        RRTConnectkConfigDefault:
          type: geometric::RRTConnect
          range: 0.5
