moveit_servo:
  ros__parameters:
    use_gazebo: true
    use_sim_time: true
    robot_link_command_frame: mm_arm_tool0
    command_in_type: "twist"
    command_out_type: "trajectory_msgs/JointTrajectory"
    planning_frame: mm_arm_root_link
    publish_period: 0.02
    low_latency_mode: true
    incoming_command_timeout: 0.25
    cartesian_command_in_topic: "/mm_arm/cartesian_cmd"
    joint_command_out_topic: "/mm_arm/joint_cmd"
    max_linear_speed: 0.4
    max_angular_speed: 1.0
    smoothing_filter_plugin: "moveit_servo/SmoothingFilters"
